# railway.toml
service = "app"
[build]
builder = "nixpacks"

# environment variables
[env]
APP_ENV = "production"

[deploy]
startCommand = "php artisan migrate --seed && php artisan serve --host=0.0.0.0 --port=$PORT"
healthcheckPath = "/"
